movieservice:
  build: .
  command: java -jar kmdb-restful-service.jar
  ports:
    - "8080:8080"
  links:
    - mongodb
  environment:
    - spring.data.mongodb.host=mongodb
    - spring.data.mongodb.port=27017

mongodb:
  image: mongo:latest
  ports:
      - "27017:27017"